# Generated by Django 3.0.6 on 2020-05-16 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55, null=True, verbose_name='название задачи')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='описание')),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('completed', 'completed')], default='active', max_length=55, null=True, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('created_by', models.ForeignKey(blank=True, default=tasks.models.get_admin, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('task_user', models.ManyToManyField(blank=True, related_name='task_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи задачи')),
            ],
        ),
    ]
